name: Linux Build
run-name: Linux Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Starting Linux Tauri Build"
      - run: cd /home/runner/work/Chrultrabook-Controller/Chrultrabook-Controller
      - run: ls ${{ github.workspace }}
      - run: echo "Finished"
